// ─── DATA.JS — QuickBite App Data ───────────────────────────────────

const PLATFORMS = [
  { id: 'all',    name: 'All',       icon: '🌐', color: '#FF6B35' },
  { id: 'zomato', name: 'Zomato',    icon: '🔴', color: '#E23744' },
  { id: 'swiggy', name: 'Swiggy',    icon: '🟠', color: '#FC8019' },
  { id: 'magicpin',name:'MagicPin',  icon: '💜', color: '#7B2FBE' },
  { id: 'eatsure',name: 'EatSure',   icon: '🟢', color: '#00A859' },
  { id: 'zepto',name: 'Zepto',   icon: '📍', color: '#113a27' },
];

const CATEGORIES = [
  { id: 'all',     label: 'All',       icon: '🍽️' },
  { id: 'pizza',   label: 'Pizza',     icon: '🍕' },
  { id: 'burger',  label: 'Burger',    icon: '🍔' },
  { id: 'sushi',   label: 'Sushi',     icon: '🍣' },
  { id: 'chinese', label: 'Chinese',   icon: '🍜' },
  { id: 'indian',  label: 'Indian',    icon: '🍛' },
  { id: 'dessert', label: 'Dessert',   icon: '🍰' },
  { id: 'healthy', label: 'Healthy',   icon: '🥗' },
  { id: 'biryani', label: 'Biryani',   icon: '🍲' },
  { id: 'rolls',   label: 'Rolls',     icon: '🌯' },
];

const PROMOS = [
  { title: '50% OFF',    sub: 'First order on Swiggy',     color: '#FF6B35', icon: '🎉', code: 'FIRST50' },
  { title: 'FREE DELIVERY', sub: 'Orders above ₹299',      color: '#00B4D8', icon: '🚀', code: 'FREEDEL' },
  { title: '30% OFF',    sub: 'Weekend special deal',       color: '#7B2FBE', icon: '🏷️', code: 'WKND30' },
];

const RESTAURANTS = [
  {
    id: 1,
    name: "Pizza Paradise",
    cuisine: "Italian • Pizza",
    categories: ['pizza'],
    platforms: ['zomato','swiggy','all'],
    rating: 4.5,
    reviews: 1240,
    time: "25-30 min",
    distance: "1.2 km",
    price: "₹200 for two",
    offer: "50% OFF up to ₹100",
    image: "🍕",
    bg: "#FFF3E0",
    favourite: false,
    tags: ["Bestseller", "Pure Veg"],
    menu: [
      { id: 101, name: "Margherita Pizza", desc: "Classic tomato, mozzarella, basil", price: 249, image: "🍕", category: "Pizzas", veg: true, bestseller: true, rating: 4.6 },
      { id: 102, name: "Farmhouse Pizza", desc: "Capsicum, mushroom, onion, corn", price: 329, image: "🍕", category: "Pizzas", veg: true, bestseller: false, rating: 4.3 },
      { id: 103, name: "Pepperoni Blast", desc: "Double pepperoni, chilli flakes", price: 399, image: "🍕", category: "Pizzas", veg: false, bestseller: true, rating: 4.7 },
      { id: 104, name: "BBQ Chicken Pizza", desc: "Grilled chicken, BBQ sauce, onions", price: 379, image: "🍗", category: "Pizzas", veg: false, bestseller: false, rating: 4.4 },
      { id: 105, name: "Garlic Bread", desc: "Toasted with garlic butter", price: 99, image: "🥖", category: "Sides", veg: true, bestseller: false, rating: 4.2 },
      { id: 106, name: "Coke 750ml", desc: "Chilled Coca-Cola", price: 59, image: "🥤", category: "Beverages", veg: true, bestseller: false, rating: 4.0 },
    ]
  },
  {
    id: 2,
    name: "Burger Barn",
    cuisine: "American • Burgers",
    categories: ['burger'],
    platforms: ['swiggy','magicpin','all'],
    rating: 4.3,
    reviews: 890,
    time: "20-25 min",
    distance: "0.8 km",
    price: "₹150 for two",
    offer: "Buy 2 Get 1 Free",
    image: "🍔",
    bg: "#FFF8E1",
    favourite: true,
    tags: ["Top Rated"],
    menu: [
      { id: 201, name: "Classic Beef Burger", desc: "Beef patty, lettuce, tomato, cheese", price: 199, image: "🍔", category: "Burgers", veg: false, bestseller: true, rating: 4.5 },
      { id: 202, name: "Veggie Delight Burger", desc: "Aloo tikki, mint chutney, veggies", price: 149, image: "🍔", category: "Burgers", veg: true, bestseller: false, rating: 4.1 },
      { id: 203, name: "Crispy Chicken Burger", desc: "Fried chicken, sriracha mayo", price: 229, image: "🍔", category: "Burgers", veg: false, bestseller: true, rating: 4.6 },
      { id: 204, name: "Double Smash Burger", desc: "Double smashed patty, special sauce", price: 299, image: "🍔", category: "Burgers", veg: false, bestseller: false, rating: 4.4 },
      { id: 205, name: "Loaded Fries", desc: "Cheese sauce, jalapeños, bacon bits", price: 129, image: "🍟", category: "Sides", veg: false, bestseller: true, rating: 4.5 },
      { id: 206, name: "Onion Rings", desc: "Crispy golden onion rings", price: 89, image: "🧅", category: "Sides", veg: true, bestseller: false, rating: 4.0 },
      { id: 207, name: "Oreo Shake", desc: "Thick oreo milkshake", price: 119, image: "🥤", category: "Shakes", veg: true, bestseller: false, rating: 4.3 },
    ]
  },
  {
    id: 3,
    name: "Sushi Studio",
    cuisine: "Japanese • Sushi",
    categories: ['sushi'],
    platforms: ['zomato','eatsure','all'],
    rating: 4.7,
    reviews: 560,
    time: "35-40 min",
    distance: "2.1 km",
    price: "₹600 for two",
    offer: "Free miso soup",
    image: "🍣",
    bg: "#E8F5E9",
    favourite: false,
    tags: ["Premium", "Trending"],
    menu: [
      { id: 301, name: "Salmon Nigiri (x2)", desc: "Fresh salmon on seasoned rice", price: 299, image: "🍣", category: "Nigiri", veg: false, bestseller: true, rating: 4.8 },
      { id: 302, name: "Tuna Roll (8pcs)", desc: "Tuna, cucumber, avocado", price: 349, image: "🍱", category: "Rolls", veg: false, bestseller: true, rating: 4.7 },
      { id: 303, name: "Veggie California Roll", desc: "Cucumber, avocado, pickled radish", price: 249, image: "🍱", category: "Rolls", veg: true, bestseller: false, rating: 4.4 },
      { id: 304, name: "Edamame", desc: "Salted steamed soybeans", price: 149, image: "🫘", category: "Starters", veg: true, bestseller: false, rating: 4.2 },
      { id: 305, name: "Miso Soup", desc: "Traditional Japanese miso broth", price: 99, image: "🍵", category: "Soups", veg: true, bestseller: false, rating: 4.1 },
    ]
  },
  {
    id: 4,
    name: "Spice Route",
    cuisine: "Indian • North Indian",
    categories: ['indian','biryani'],
    platforms: ['zomato','swiggy','magicpin','eatsure','all'],
    rating: 4.4,
    reviews: 2100,
    time: "30-40 min",
    distance: "1.5 km",
    price: "₹300 for two",
    offer: "20% OFF on orders above ₹499",
    image: "🍛",
    bg: "#FCE4EC",
    favourite: true,
    tags: ["Most Loved", "Bestseller"],
    menu: [
      { id: 401, name: "Butter Chicken", desc: "Tender chicken in rich tomato gravy", price: 299, image: "🍛", category: "Mains", veg: false, bestseller: true, rating: 4.7 },
      { id: 402, name: "Dal Makhani", desc: "Slow-cooked black lentils, cream", price: 199, image: "🫕", category: "Mains", veg: true, bestseller: true, rating: 4.6 },
      { id: 403, name: "Chicken Biryani", desc: "Aromatic basmati, saffron, spices", price: 349, image: "🍲", category: "Biryani", veg: false, bestseller: true, rating: 4.8 },
      { id: 404, name: "Veg Biryani", desc: "Mixed vegetables, basmati, kewra", price: 249, image: "🍲", category: "Biryani", veg: true, bestseller: false, rating: 4.3 },
      { id: 405, name: "Garlic Naan (x2)", desc: "Tandoor-baked with garlic butter", price: 79, image: "🫓", category: "Breads", veg: true, bestseller: false, rating: 4.4 },
      { id: 406, name: "Paneer Tikka Masala", desc: "Cottage cheese in spiced tomato gravy", price: 279, image: "🧀", category: "Mains", veg: true, bestseller: false, rating: 4.5 },
      { id: 407, name: "Raita", desc: "Yogurt with cucumber, cumin", price: 59, image: "🥣", category: "Sides", veg: true, bestseller: false, rating: 4.0 },
    ]
  },
  {
    id: 5,
    name: "Dragon Bowl",
    cuisine: "Chinese • Asian Fusion",
    categories: ['chinese'],
    platforms: ['swiggy','zomato','all'],
    rating: 4.2,
    reviews: 730,
    time: "25-35 min",
    distance: "1.8 km",
    price: "₹250 for two",
    offer: "Free spring rolls above ₹399",
    image: "🍜",
    bg: "#E3F2FD",
    favourite: false,
    tags: ["Quick Delivery"],
    menu: [
      { id: 501, name: "Hakka Noodles", desc: "Wok-tossed noodles, veggies, soy", price: 179, image: "🍜", category: "Noodles", veg: true, bestseller: true, rating: 4.4 },
      { id: 502, name: "Chicken Manchurian", desc: "Crispy chicken, manchurian sauce", price: 249, image: "🍗", category: "Starters", veg: false, bestseller: true, rating: 4.5 },
      { id: 503, name: "Veg Spring Rolls (6pcs)", desc: "Crispy rolls with chilli sauce", price: 149, image: "🥟", category: "Starters", veg: true, bestseller: false, rating: 4.2 },
      { id: 504, name: "Chicken Fried Rice", desc: "Egg fried rice with chicken strips", price: 199, image: "🍚", category: "Rice", veg: false, bestseller: false, rating: 4.3 },
    ]
  },
  {
    id: 6,
    name: "Green Bowl",
    cuisine: "Healthy • Salads & Bowls",
    categories: ['healthy'],
    platforms: ['eatsure','zomato','all'],
    rating: 4.6,
    reviews: 410,
    time: "20-30 min",
    distance: "0.6 km",
    price: "₹350 for two",
    offer: "10% cashback with Paytm",
    image: "🥗",
    bg: "#E8F5E9",
    favourite: false,
    tags: ["Healthy", "Low Calorie"],
    menu: [
      { id: 601, name: "Greek Salad Bowl", desc: "Feta, olives, cucumber, tomato", price: 249, image: "🥗", category: "Salads", veg: true, bestseller: true, rating: 4.6 },
      { id: 602, name: "Quinoa Power Bowl", desc: "Quinoa, chickpeas, avocado, greens", price: 299, image: "🥣", category: "Bowls", veg: true, bestseller: true, rating: 4.7 },
      { id: 603, name: "Grilled Chicken Wrap", desc: "Grilled chicken, lettuce, hummus", price: 279, image: "🌯", category: "Wraps", veg: false, bestseller: false, rating: 4.4 },
      { id: 604, name: "Acai Smoothie Bowl", desc: "Acai, banana, granola, berries", price: 329, image: "🫐", category: "Smoothie Bowls", veg: true, bestseller: false, rating: 4.5 },
    ]
  },
  {
    id: 7,
    name: "Sweet Treats",
    cuisine: "Desserts • Bakery",
    categories: ['dessert'],
    platforms: ['swiggy','magicpin','all'],
    rating: 4.5,
    reviews: 980,
    time: "15-20 min",
    distance: "0.4 km",
    price: "₹150 for two",
    offer: "Buy 3 Get 1 Free on cakes",
    image: "🍰",
    bg: "#F3E5F5",
    favourite: false,
    tags: ["Fast Delivery", "Pure Veg"],
    menu: [
      { id: 701, name: "Chocolate Lava Cake", desc: "Warm cake with molten chocolate", price: 149, image: "🎂", category: "Cakes", veg: true, bestseller: true, rating: 4.8 },
      { id: 702, name: "Tiramisu", desc: "Classic Italian coffee dessert", price: 199, image: "🍮", category: "Italian", veg: true, bestseller: false, rating: 4.6 },
      { id: 703, name: "Gulab Jamun (x4)", desc: "Soft milk dumplings in sugar syrup", price: 89, image: "🍡", category: "Indian Sweets", veg: true, bestseller: true, rating: 4.5 },
      { id: 704, name: "New York Cheesecake", desc: "Creamy classic with berry compote", price: 229, image: "🍰", category: "Cakes", veg: true, bestseller: false, rating: 4.7 },
      { id: 705, name: "Kulfi Falooda", desc: "Pistachio kulfi with falooda", price: 119, image: "🍦", category: "Indian Sweets", veg: true, bestseller: false, rating: 4.4 },
    ]
  },
  {
    id: 8,
    name: "Roll Station",
    cuisine: "Street Food • Rolls & Wraps",
    categories: ['rolls'],
    platforms: ['swiggy','zomato','magicpin','all'],
    rating: 4.1,
    reviews: 1560,
    time: "15-20 min",
    distance: "0.3 km",
    price: "₹100 for two",
    offer: "₹30 off on 3+ items",
    image: "🌯",
    bg: "#FFF3E0",
    favourite: false,
    tags: ["Super Fast", "Budget Friendly"],
    menu: [
      { id: 801, name: "Egg Roll", desc: "Egg, onion, green chutney wrap", price: 79, image: "🌯", category: "Egg Rolls", veg: false, bestseller: true, rating: 4.3 },
      { id: 802, name: "Paneer Roll", desc: "Grilled paneer, capsicum, chutney", price: 99, image: "🌯", category: "Veg Rolls", veg: true, bestseller: true, rating: 4.2 },
      { id: 803, name: "Chicken Tikka Roll", desc: "Tandoori chicken, onion, mint chutney", price: 129, image: "🌯", category: "Non-Veg Rolls", veg: false, bestseller: false, rating: 4.4 },
      { id: 804, name: "Double Egg Roll", desc: "Two eggs, extra cheese, sauces", price: 109, image: "🌯", category: "Egg Rolls", veg: false, bestseller: false, rating: 4.1 },
    ]
  }
];

const COUPONS = [
  { code: 'FIRST50', discount: 50, type: 'percent', minOrder: 199, desc: '50% OFF on your first order' },
  { code: 'FREEDEL', discount: 0,  type: 'delivery', minOrder: 299, desc: 'Free delivery on orders above ₹299' },
  { code: 'WKND30', discount: 30,  type: 'percent', minOrder: 399, desc: '30% OFF this weekend' },
  { code: 'DS100',  discount: 100, type: 'flat',    minOrder: 499, desc: 'Flat ₹100 off on orders above ₹499' },
  { code: 'SAVE20', discount: 20,  type: 'percent', minOrder: 249, desc: '20% off on selected restaurants' },
];

const PAST_ORDERS = [
  {
    id: 'QB20240101',
    restaurant: 'Spice Route',
    items: ['Butter Chicken', 'Garlic Naan x2', 'Dal Makhani'],
    total: 577,
    date: '2025-12-15',
    status: 'Delivered',
    icon: '🍛',
    platform: 'Swiggy'
  },
  {
    id: 'QB20240089',
    restaurant: 'Pizza Paradise',
    items: ['Margherita Pizza', 'Garlic Bread', 'Coke 750ml'],
    total: 407,
    date: '2025-12-10',
    status: 'Delivered',
    icon: '🍕',
    platform: 'Zomato'
  },
  {
    id: 'QB20240077',
    restaurant: 'Burger Barn',
    items: ['Crispy Chicken Burger', 'Loaded Fries'],
    total: 358,
    date: '2025-12-05',
    status: 'Delivered',
    icon: '🍔',
    platform: 'Swiggy'
  },
];

const OFFERS = [
  { title: '50% OFF', sub: 'First order on Swiggy', code: 'FIRST50', color: '#FF6B35', icon: '🎉', valid: 'Till 31st Dec 2025' },
  { title: 'FREE DELIVERY', sub: 'All orders above ₹299', code: 'FREEDEL', color: '#00B4D8', icon: '🚀', valid: 'Always active' },
  { title: '30% OFF', sub: 'Weekend Special', code: 'WKND30', color: '#7B2FBE', icon: '🏷️', valid: 'Sat-Sun only' },
  { title: '₹100 FLAT OFF', sub: 'Orders above ₹499', code: 'QB100', color: '#E23744', icon: '💰', valid: 'Limited time' },
  { title: '20% OFF', sub: 'Selected restaurants', code: 'SAVE20', color: '#00A859', icon: '✨', valid: 'This week' },
];